### ISSUE TITLE
Can't find views

### ISSUE THREAD

**Issue by eduardoarandah** [eduardoarandah/medialibrary-dropzone-for-laravel-backpack#2]
![image](https://user-images.githubusercontent.com/4065733/89108252-681a6100-d3fc-11ea-87f7-18856a80ad13.png)

Composer:

```
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/",
            "EduardoArandaH\\MediaLibraryDropzone\\": "packages/eduardoarandah/medialibrarydropzone/src/"

        }
    },

```

Files:

![image](https://user-images.githubusercontent.com/4065733/89108316-f55db580-d3fc-11ea-94ab-31340bdc4984.png)

**Comment by tabacitu** [comment]
Ah, right! In order to use a field from a package, you have to define the `view_namespace` too. So it's:

```diff
        CRUD::addField([
            'name' => 'pictures',
            'type' => 'medialibrary-dropzone',
+           'view_namespace' => 'medialibrary-dropzone::fields',
            'url' => "/product/{$this->crud->getCurrentEntry()->id}/picture"
        ]);
```

**Comment by tabacitu** [comment]
Fixed by #4

**Comment by eduardoarandah** [comment]
> Ah, right! In order to use a field from a package, you have to define the `view_namespace` too. So it's:
> 
> ```diff
>         CRUD::addField([
>             'name' => 'pictures',
>             'type' => 'medialibrary-dropzone',
> +           'view_namespace' => 'medialibrary-dropzone::fields',
>             'url' => "/product/{$this->crud->getCurrentEntry()->id}/picture"
>         ]);
> ```

so, the user will have to use that when defining the field?

**Comment by tabacitu** [comment]
> so, the user will have to use that when defining the field?

Yes. 

---

In a future Backpack version (4.2 or maybe 5.0) we will probably allow package developer to register their custom view directories in a queue. So that Backpack looks for fields/columns/widgets/etc:
- inside the user folder
- (NEW) inside addon folders
- inside the backpack package folder

That way there could also be packages that actually overwrite the default Backpack views, without publishing anything in userland.

But it's a slippery slope, because then you have to manually/automatically manage the _addon folder order_. Why would your package views be loaded before someone else's? Tricky. 

But hey - for now, `view_namespace` should work just fine.
